### ISSUE TITLE
'::max_align_t' has not been declared

### ISSUE THREAD

**Issue by Legorock** [CompOpt4Apps/IEGenLib#47]
Hi, 

I got many errors while compiling with gcc 5.4. Basically all of them caused by missing <cstddef> headerfile. I had to manually insert every source file `#include <cstddef>` as a quick and dirty solution. Is it possible to fix this issue?

Regards

**Comment by king-mahdi** [comment]
Master branch is getting building with gcc5.4 without any issues now. Unfortunately, I do not remember what change helped to solve this issue, but I have changed the configure file quite a bit for various reasons including updating isl version, and adding more generic string input format for parser. One of those changes should have helped solve this issue as well.
